### ISSUE TITLE
Themes not installed

### ISSUE THREAD

**Issue by abhishekcs0** [MyMacQt/mymacqt#1]
apple-monterery theme:  Installation of /tmp/UJqbuQ-Apple-Monterey-Dark.tar.xz failed: Could not install dependency: 'kns://plasmoids.knsrc/api.kde-look.org/1916655'

macsonoma: No items Found 

kde plasma version : 5.27.11
kde frameworks version : 5.115.0
qt version : 5.15.12
kernal version : 6.6.26-1-MANJARO (64-bit)
graphics platform : x11

**Comment by MyMacQt** [comment]
https://github.com/vinceliuice/MacSonoma-kde

**Comment by abhishekcs0** [comment]
Thanks, I Downloaded the themes from google and moved them to .local > look and feel, and it worked
